title:            "Pixelastic"
description:      "Personal blog of Tim Carry. Posting mostly on tech-related stuff."
tagline:          "You can cut our wings but we will always remember what it was like to fly."
url:              http://blog.pixelastic.com
base_url:         blog.pixelastic.com
source: "app"
author:
  name:           "Tim Carry"
  url:            https://twitter.com/pixelastic

# Dependencies
markdown:         redcarpet
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
paginate:         5

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/pixelastic/blog.pixelastic.com

# Build
timezone:         "Europe/Paris"
encoding:         "utf-8"

# Algolia
algolia:
  application_id: "O3F8QXYK6R"
  index_name: "blog"

# Custom vars
version:          3.0.0
