title: Pixelastic
email: tim@pixelastic.com
description: >-
  Personal blog of Tim Carry. Posting mostly on tech-related stuff.
baseurl: ""
url: "https://blog.pixelastic.com"
twitter_username: pixelastic
github_username: pixelastic

# Build settings
source: blog
destination: dist
timezone: Europe/Paris
theme: minima

plugins:
  - jekyll-postcss
  - jekyll-purgecss
