#!/usr/bin/env bash
npm install
grunt build
rsync \
  --recursive \
  --verbose \
  --archive \
  --update \
  --delete \
  --prune-empty-dirs \
  --compress \
  ./dist/build-full/ \
  pixelastic:/var/www/pixelastic.com/blog.pixelastic.com/

